services:
  backend:
    build: .
    container_name: haven_tg
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - haven_network

networks:
  haven_network: